name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, Any CPU]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: MSBuild of plugin dll
      working-directory: .\
      run: msbuild GrepBugPluginNpp.vcxproj /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: Archive artifacts for x64
      if: matrix.build_platform == 'x64'
      uses: actions/upload-artifact@v1
      with:
          name: plugin_dll_x64
          path: GrepBugsPluginNpp\bin\${{ matrix.build_platform }}\${{ matrix.build_configuration }}\GrepBugsPluginNpp.dll

    - name: Archive artifacts for Any CPU
      if: matrix.build_platform == 'Any CPU'
      uses: actions/upload-artifact@v1
      with:
          name: plugin_dll_x86
          path: GrepBugsPluginNpp\bin\${{ matrix.build_configuration }}\GrepBugsPluginNpp.dll
